# mind/config/default.yaml
# Default configuration for MIND project

# Data configuration
data:
  # Data paths
  neural_path: "data/raw/SFL13_5_8112021_002_new.mat"
  behavior_path: "data/raw/SFL13_5_8112021_002_new.xlsx"

  # Binary classification (no footstep vs. contralateral footstep)
  binary_task: true

  # Sliding window parameters
  window_size: 15
  step_size: 1

  # Train/val/test split
  test_size: 0.15
  val_size: 0.15
  random_state: 42

# Model configuration
models:
  # Random Forest
  random_forest:
    n_estimators: 200
    max_depth: 30
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: "sqrt"
    class_weight: "balanced"
    optimize_hyperparams: false
    random_state: 42

  # SVM
  svm:
    C: 1.0
    kernel: "rbf"
    gamma: "scale"
    class_weight: "balanced"
    apply_pca: true
    pca_components: 0.95
    optimize_hyperparams: false
    random_state: 42

  # MLP
  mlp:
    hidden_layer_sizes: [64, 128, 32]
    activation: "relu"
    solver: "adam"
    alpha: 0.0001
    batch_size: "auto"
    learning_rate: "adaptive"
    learning_rate_init: 0.001
    max_iter: 500
    early_stopping: true
    validation_fraction: 0.1
    optimize_hyperparams: false
    random_state: 42

  # FCNN
  fcnn:
    hidden_sizes: [256, 128, 64]
    dropout_rates: [0.3, 0.3, 0.3]
    batch_norm: true
    learning_rate: 0.001
    weight_decay: 0.00001
    batch_size: 32
    num_epochs: 100
    early_stopping_patience: 15
    random_state: 42

  # CNN
  cnn:
    filter_sizes: [64, 128, 256]
    kernel_size: 3
    use_residual: true
    use_batch_norm: true
    learning_rate: 0.001
    weight_decay: 0.00001
    batch_size: 32
    num_epochs: 100
    early_stopping_patience: 15
    use_focal_loss: true
    focal_loss_gamma: 2.0
    random_state: 42

# Visualization configuration
visualization:
  # Signal visualization
  signals:
    num_neurons: 20
    figsize: [20, 15]

  # Feature importance visualization
  feature_importance:
    top_n: 20
    figsize: [12, 8]

  # Performance visualization
  performance:
    figsize: [12, 8]

# Output configuration
output:
  # Output directory
  dir: "results"

  # Model directory
  model_dir: "results/models"

  # Visualization directory
  viz_dir: "results/visualizations"

  